Algoritmo "exercicioFaccat5"
// Disciplina   : [L?gica da programa??o com javascript]
// Professor   : Jailson Costa dos Santos
// Descri??o   :  Ler o antecessor de um n?mero
// Autor(a)    : John wesley
// Data atual  : 24/03/2024
Var
   numero, antecessor:inteiro

Inicio
   escreval("Digite um n?mero:")
   leia(numero)
   antecessor<- numero -1
   Escreval("O antecessor do n?mero:", numero ," , ?", antecessor)

Fimalgoritmo