Algoritmo "exercicioFaccat27"
// Disciplina   : [L?gica de programa??o com javascript]
// Professor   : Jailson Costa Dos Santos
// Descri??o   : Ler um n?mero ? informar se ele ? postivo ou negativo
// Autor(a)    : John wesley
// Data atual  : 24/03/2024
Var
 numero:inteiro

Inicio
 escreval("Digite um N?mero")
 leia(numero)
 se numero >=0 entao
 escreval("N?mero ? positivo")
 senao
 se numero <0 entao
 escreval("N?mero ? negativo")
 fimse
  fimse
Fimalgoritmo