Algoritmo "exercicioFaccat12"
// Disciplina   : [Lógica da programação]
// Professor   : Jailson Costa Santos
// Descrição   : Ler os graus fahrenheit em graus celsius
// Autor(a)    : John wesley
// Data atual  : 24/03/2024
Var

 celsius,fahrenheit:real

Inicio
  Escreval("Digite a temperatura em fahrenheit:")
   leia(fahrenheit)
   celsius<- (fahrenheit - 32) * (5/9)
   escreval("A temperatura em graus Celsius é de:" , celsius)
Fimalgoritmo