Algoritmo "exercicioFaccat15"
// Disciplina   : [Lógica de programação com javascript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Ler um número é informar se ele é postivo ou negativo
// Autor(a)    : John wesley
// Data atual  : 24/03/2024
Var
 numero:inteiro

Inicio
 escreval("Digite um Número")
 leia(numero)
 se numero >=0 entao
 escreval("Número é positivo")
 senao
 se numero <0 entao
 escreval("Número é negativo")
 fimse
  fimse
Fimalgoritmo